[project]
name = "ComfyUI_AITECCAFE_Toolkit"
description = "This custom node includes the following functions: LLM Loader,LLM Chat,LLM Vision Loader,LLM Vision,Image Loader,Media Loader,String Merge,ChatGPT Chat,Image Moderation,NSFW Checker.LLM now supports Qwen 3.5 and Gemma 4 by updating llama-cpp-python to the latest version."
version = "1.2.5"
license = { file = "LICENSE" }
dependencies  = ["openai","opencv-python","opennsfw2","tensorflow"]

[project.urls]
Repository = "https://github.com/AI-TEC/ComfyUI-AITECCAFE-Toolkit"
Documentation = "https://github.com/AI-TEC/ComfyUI-AITECCAFE-Toolkit/wiki"
"Bug Tracker" = "https://github.com/AI-TEC/ComfyUI-AITECCAFE-Toolkit/issues"

[tool.comfy]
PublisherId = "aiteccafe"
DisplayName = "ComfyUI_AITECCAFE_Toolkit"
Icon = ""
includes = [] 
