[project]
name = "aiteccafe-toolkit"
description = "This custom node includes the following functions: Chat_GPT, image_moderation, media_loader, merge_strings, sequential_image_loader, NSFW Checker."
version = "1.1.1"
license = { file = "LICENSE" }
dependencies  = ["openai","opencv-python","opennsfw2","tensorflow"]

[project.urls]
Repository = "https://github.com/AI-TEC/ComfyUI-AITECCAFE-Toolkit"

[tool.comfy]
PublisherId = "aiteccafe"
DisplayName = "ComfyUI-AITECCAFE-Toolkit"
Icon = ""


