# This file can be empty, but it's good practice to aggregate mappings here.

# Import mappings from all node files
from .AITEC_Chat_GPT import NODE_CLASS_MAPPINGS as CHATGPT_NODES, NODE_DISPLAY_NAME_MAPPINGS as CHATGPT_NAMES
from .AITEC_media_loader import NODE_CLASS_MAPPINGS as MEDIA_LOADER_NODES, NODE_DISPLAY_NAME_MAPPINGS as MEDIA_LOADER_NAMES
from .AITEC_merge_strings import NODE_CLASS_MAPPINGS as MERGE_STRINGS_NODES, NODE_DISPLAY_NAME_MAPPINGS as MERGE_STRINGS_NAMES
from .AITEC_sequential_image_loader import NODE_CLASS_MAPPINGS as SEQ_IMAGE_LOADER_NODES, NODE_DISPLAY_NAME_MAPPINGS as SEQ_IMAGE_LOADER_NAMES
from .AITEC_image_moderation import NODE_CLASS_MAPPINGS as IMAGE_MODERATION_NODES, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_MODERATION_NAMES

# Combine all mappings into single dictionaries
NODE_CLASS_MAPPINGS = {
    **CHATGPT_NODES,
    **MEDIA_LOADER_NODES,
    **MERGE_STRINGS_NODES,
    **SEQ_IMAGE_LOADER_NODES,
    **IMAGE_MODERATION_NODES,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **CHATGPT_NAMES,
    **MEDIA_LOADER_NAMES,
    **MERGE_STRINGS_NAMES,
    **SEQ_IMAGE_LOADER_NAMES,
    **IMAGE_MODERATION_NAMES,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

