from .ComfyUI_AITECCAFE_Toolkit import (
    NODE_CLASS_MAPPINGS as TOOLKIT_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TOOLKIT_DISPLAY_MAPPINGS
)

from .ComfyUI_AITEC_LocalLLM import (
    NODE_CLASS_MAPPINGS as LLM_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LLM_DISPLAY_MAPPINGS
)

NODE_CLASS_MAPPINGS = {
    **TOOLKIT_CLASS_MAPPINGS,
    **LLM_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **TOOLKIT_DISPLAY_MAPPINGS,
    **LLM_DISPLAY_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]